project:
  type: default

format:
  pdf:
    documentclass: book
    classoption:
      - openany
    pdf-engine: xelatex
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    linkcolor: black
    urlcolor: black
    citecolor: black
    geometry:
      - top=1in
      - right=1in
      - left=1.2in
      - bottom=1in
    include-in-header:
      - text: |
          \usepackage{xeCJK}
          \xeCJKsetup{CJKspace=true}
          \setCJKmainfont{NanumGothic}
          \setCJKsansfont{NanumGothicBold}
          \setCJKmonofont{NanumGothicCoding}
          \usepackage{setspace}
          \onehalfspacing
    keep-tex: true

bibliography: book.bib
biblio-style: apalike

metadata:
  title: "AngraMyNew: The Art of Creation and Being"
  author: "Angra Collective"
